services:

  sqlserver:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: trackflowhub-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    image: wichopedia/trackflow-backend:v3.0.0
    container_name: trackflowhub-backend
    restart: always
    depends_on:
      - sqlserver
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    image: wichopedia/trackflow-frontend:v3.0.0
    container_name: trackflowhub-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  sqlserver_data: