services:

  sqlserver:
    build: .
    container_name: trackflowhub-db

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      
    ports:
      - "1434:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: